#!/usr/pkg/bin/bash

SVC=/arpa/gm/g/grobe0ba/opt/iceland/command
LOG=/arpa/gm/g/grobe0ba/combot/log/current
SVCDIR=/arpa/gm/g/grobe0ba/opt/iceland/service/combot

case "${1}" in
    start)
	${SVC}/svc -u "${SVCDIR}"
	;;
    stop)
	${SVC}/svc -d "${SVCDIR}"
	;;
    restart)
	${SVC}/svc -du "${SVCDIR}" "${SVCDIR}"
	;;
    status)
	${SVC}/svstat "${SVCDIR}" | cut -d':' -f2 | sed -e 's/^[ \t]*//'
	;;
    log)
	clear;
	tail -f "${LOG}" | ${SVC}/tai64nlocal
	;;
    kill)
	svc -td "${SVCDIR}" "${SVCDIR}"
	;;
esac
