#!/usr/local/bin/bash

ROOM=bar
PORT=64453

if [ -e comsock ]; then rm comsock; fi

function cleanup
{
	echo Bailing out...
	pkill socat
	pkill cat
	BAIL=1
}
trap cleanup SIGTERM SIGKILL SIGQUIT SIGINT


function pubmsg
{
	LINE=$1
	PERSON=`echo "$LINE" | gcut -d ' ' -f 1`
	LINE=`echo "$LINE" | gcut -d ' ' -f 1 --complement`

	echo "Public Message from $PERSON: $LINE"
	return
}

function msg
{
	LINE=$1
	PERSON=`echo "$LINE" | gcut -d ' ' -f 1 | sed -e 's/://'`
	LINE=`echo "$LINE" | gcut -d' ' -f 1 --complement`

	echo "Message from $PERSON: $LINE"

	if [ "$PERSON" == "grobe0ba@faeroes" ]; then
		COMMAND=`echo "$LINE" | gcut -d ' ' -f 1`
		EXTRA=`echo "$LINE" | gcut -d ' ' -f 1 --complement`

		case "$COMMAND" in
			quit)
				echo -en "q\n\n" >&10
				pkill socat
				;;
			say)
				echo -en " $EXTRA\n\n\n" >&10
				;;
			msg)
				TO=`echo "$LINE" | gcut -d ' ' -f 2,3`
				MSG=`echo "$LINE" | gcut -d ' ' -f 1,2,3 --complement`
				echo -en "s$TO\n$MSG\n" >&10
				;;
			go)
				echo -en "g$EXTRA\n\n" >&10;
				;;
			'?')
				echo -en "sgrobe0ba@faeroes\nIncorrect function\n" >&10
				;;
		esac
	fi
	return
}

function send_ping
{
	echo PING
	return
}

#Establish PTY->TCP socket link using socat
socat exec:'ssh -t gropebot@sdf.org com',stderr,pty,ctty,sigquit,sigint,raw,echo=0 TCP-LISTEN:$PORT,bind=127.0.0.1,fork &
#Grab PID for socat for loop monitoring
PID=$!

#Have to wait a bit for everything to clear up
sleep 2;

#Open the TCP socket, file descriptor 10
exec 10<>/dev/tcp/127.0.0.1/$PORT

#Join the room
echo -en "g$ROOM\n" >&10

#Wait again for everything to settle down
sleep 1;
while `kill -s 0 $PID`
do
	read -u 10 LINE
	LINE=`echo "$LINE" | killcolor`
	LINE=`echo "$LINE" | tr -cd '[[:alnum:][:space:]@]'`
	echo "$LINE"
	if `grep -q grobe0ba <(echo "$LINE")`; then
		send_ping "$LINE"
	fi
	if `grep -q joined <(echo "$LINE")`; then
		if `grep -q elita <(echo "$LINE")`; then
			echo -en "egrabs elita's ass\n\n" >&10
		fi
		if `grep -q felix <(echo "$LINE")`; then
			echo -en "emotorboats felix tits\n\n" >&10
		fi
		if `grep -q hapiworm <(echo "$LINE")`; then
			echo -en "ekisses hapiworm under the starlight\n\n" >&10
		fi
	fi
	msg "$LINE"
done
